### ISSUE TITLE
UnsatisfiedLinkError with PDFium on Android 15 Emulator with 16 KB Page Size

### ISSUE THREAD

**Issue by yd-threra-and** [DImuthuUpe/AndroidPdfViewer#1191]
### Environment
- **Library version**: 3.2.0-beta.1
- **Android version**: 15 (Vanilla Ice Cream)
- **Emulator**: 16 KB page size

### Steps to Reproduce
1. Create an Android emulator with 16 KB page size following the steps in the [Android Developers Guide](https://developer.android.com/guide/practices/page-sizes#16kb-emulator).
2. Use the PDF Viewer library to load a PDF document with the following code from some fragment from our demo test app:
    ```kotlin
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        val outputFile = File(requireContext().filesDir, "sample.pdf")
        if (!outputFile.exists()) {
            try {
                val inputStream: InputStream = requireContext().assets.open("sample.pdf")
                val outputStream = FileOutputStream(outputFile)
                val buffer = ByteArray(1024)
                var length: Int
                while (inputStream.read(buffer).also { length = it } > 0) {
                    outputStream.write(buffer, 0, length)
                }
                outputStream.close()
                inputStream.close()
            } catch (e: IOException) {
                e.printStackTrace()
            }
        }

        binding.pdfView.fromFile(outputFile)
            .enableSwipe(true)
            .swipeHorizontal(false)
            .enableDoubletap(true)
            .defaultPage(0)
            .onLoad { nbPages -> /* Do something on load complete */ }
            .onPageError { page, t -> /* Handle page error */ }
            .load()
    }
    ```
3. Observe the error.

### Error Log
java.lang.UnsatisfiedLinkError: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)
at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:135)
at com.github.barteksc.pdfviewer.source.FileSource.createDocument(FileSource.java:38)
at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:53)
at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:27)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)

### Additional Context
This issue affects applications running on Android 15 with 16 KB page size, not limited to those targeting Android 15. The issue is critical as it impacts our project's ability to function correctly on these environments.

### Request
We would appreciate any guidance on resolving this issue or information on upcoming fixes. We are willing to assist with testing or contributing to a solution if needed.

Thank you for your attention to this matter.

**Comment by JakeSteam** [comment]
Just a heads-up that [this fork (of a fork (of a fork))](https://github.com/lion1988dev/PdfiumAndroid/pull/4) seems to add 16KB support. Hopefully it'll eventually get merged in, and actually be usable! )

**Comment by yd-threra-and** [comment]
@JakeSteam Thanks for the heads-up about the fork that addresses the 16KB page size alignment issue.

Do you know if there's an estimated timeline for merging this fix into this repository? Alternatively, is the fork stable enough to consider temporarily integrating into our project?

**Comment by JakeSteam** [comment]
@yd-threra-and I ended up forking lion1988dev's [`AndroidPdfViewer`](https://github.com/lion1988dev/AndroidPdfViewer), and updating the dependency to v-mas' [`PdfiumAndroid`](https://github.com/v-mas/PdfiumAndroid/) fork with 16KB support, and it works well in my project.

I ultimately decided that depending on all these forks of forks from abandoned GitHub accounts was too important for a mission critical component of our app (PDF viewing), so created a private (company-owned, sorry!) repo with them both. This is then included as a submodule, to ensure it won't unexpectedly disappear. This solution seems the safest!

**Comment by yd-threra-and** [comment]
@JakeSteam,
Thanks a lot for the detailed info - much appreciated!

Just to clarify a few things based on your solution:

- Did you fork both AndroidPdfViewer and PdfiumAndroid into your organization/private repo?

- Any tips on linking the two cleanly inside the project? (Besides using Git submodules — wondering if you explored AARs or other strategies.)

- You mentioned "actually maintained image-based PDF renderers" as an alternative — could you share any specific libraries you’ve tried or recommend? We don’t require clickable links, so switching to an image-based viewer could work for us.

(We're just using AndroidPdfViewer for basic zoomable viewing in fragments, no clickable links or Compose integration.)

Thanks again — this is super helpful!

**Comment by JakeSteam** [comment]
So, I used a single repo with a `AndroidPdfViewer` module, which then depended on a `PdfiumAndroid` module I just downloaded from the relevant 16KB fork. The overall repo was then included as a git submodule in the actual app, which is also under my company's organisation, and the `AndroidPdfViewer` module depended on (which then depended on `PdfiumAndroid`).

However, I later decided to instead use created `.aar` files (to avoid rebuilds) as you mentioned, and haven't settled on any process better than "uncomment the dependency, change the submodule, republish the `.aar`s, and a copy them across" yet! I'm optimistic I'll probably never manually change these files, except to replace the whole thing with a maintained fork one day.

If you don't need clickable links, there are MUCH better options available. Here's the verbatim notes from my little investigation a few weeks ago, I integrated most and Pdf-Viewer & Bouquet were my favourites:
> ## Alternative libraries
> 
> Whilst there are lots of libraries, they almost all use [android.graphics.pdf](https://developer.android.com/reference/android/graphics/pdf/package-summary) under the hood which renders PDF pages into images, and loses the links:
> * [AndroidX](https://developer.android.com/jetpack/androidx/releases/pdf): Only supports Android versions STUV, and renders as images, is alpha.
> * [Bouquet](https://github.com/GRizzi91/bouquet/issues): Built well, but renders as images and overrides any tap events.
>   * The author also wrote [a Medium guide](https://medium.com/telepass-digital/how-to-show-a-pdf-with-jetpack-compose-74fc773adbd0) that we might end up needing.
> * [Pdf-Viewer](https://github.com/afreakyelf/Pdf-Viewer): Lightweight, but renders as images.
> * [PdfBox](https://github.com/TomRoush/PdfBox-Android): Slow, ported library. Renders as images but provides access to (some) underlying data.
> * [Nutrient](https://www.nutrient.io/blog/open-pdf-android/): A (paid & expensive!) library that is massively overkill, and lacking info on linking.
> * Rendering PDFs in a webview: May be viable with "pdf.js", it looks [pretty awkward](https://github.com/loosemoose/androidpdf) though.

Hope that helps!

**Comment by marain87** [comment]
I've updated [PDFiumAndroid](https://github.com/marain87/PdfiumAndroid) project to support 16KB memory page sizes by upgrading the Gradle plugin and NDK. This is intended as a temporary solution to help developers prepare for Android 15/16.

Check out the sample (3.2.6) : https://github.com/marain87/AndroidPdfViewer

**Comment by marain87** [comment]
Hi @Leedwon , it seems there's an issue with accessing the PdfiumAndroid JAR files on JitPack, as they appear to have been removed. 

To address this, I've merged the '16KB' branch into the master and published a new version of [PdfiumAndroid](https://github.com/marain87/PdfiumAndroid) (v1.9.7). Additionally, there is a new version of [AndroidPdfViewer](https://github.com/marain87/AndroidPdfViewer) available (v3.2.7). 

I would also suggest creating a fork of the repository as your own backup.

**Comment by subhajit-rajak** [comment]
Thank you for pointing that out @marain87 . Can you do me a little favor and attach the entire dependency in your next reply. I couldn't find it anywhere. It will be helpful to others as well. Thank you

**Comment by marain87** [comment]
@subhajit-rajak The version you should use 'com.github.marain87:AndroidPdfViewer:3.2.7', which is a fork of the project. If 'lion1988dev' approves and merges the changes, there is a possibility that it will change to archived. 
I would highly recommend that you create a local backup of the version you are using to make sure you have continued access to the code.

@sandipkush10 Are you using the correct dependency? arm64-v8a/x86_64 libs are aligned.  (only arm64-v8a/x86_64 libs need to be aligned for 16KB).

<img width="1239" height="296" alt="Image" src="https://github.com/user-attachments/assets/48888855-5247-4ffc-ae0f-25e86b104bef" />

**Comment by subhajit-rajak** [comment]
Thank you @marain87.

**Comment by sandipkush10** [comment]
@marain87 Yes I am using correct implementation('com.github.marain87:AndroidPdfViewer:3.2.7') dependency with maven { url 'https://jitpack.io' } 

<img width="2920" height="1214" alt="Image" src="https://github.com/user-attachments/assets/6f652285-bba0-4e20-b6e0-27df5ef669d1" />

**Comment by marain87** [comment]
@sandipkush10 
Ref to [https://developer.android.com/guide/practices/page-sizes?authuser=3#identify-native-code](https://developer.android.com/guide/practices/page-sizes?authuser=3#identify-native-code)
Regarding the 16KB alignment, the "No" in the "Compressed" column of the documentation is not indicative of the issue.

I've used the elf_alignment_test script, as suggested in the Android developer guide, to verify this in my project in the previous reply. You can find the script and instructions here: [https://developer.android.com/guide/practices/page-sizes?authuser=3#alignment-use-script](https://developer.android.com/guide/practices/page-sizes?authuser=3#alignment-use-script)

If you still have any issues with it, you may try another fork project. ref to #1229

**Comment by Maromax-4002** [comment]
> [@yd-threra-and](https://github.com/yd-threra-and) I ended up forking lion1988dev's [`AndroidPdfViewer`](https://github.com/lion1988dev/AndroidPdfViewer), and updating the dependency to v-mas' [`PdfiumAndroid`](https://github.com/v-mas/PdfiumAndroid/) fork with 16KB support, and it works well in my project.
> 
> I ultimately decided that depending on all these forks of forks from abandoned GitHub accounts was too important for a mission critical component of our app (PDF viewing), so created a private (company-owned, sorry!) repo with them both. This is then included as a submodule, to ensure it won't unexpectedly disappear. This solution seems the safest!
> 
> If you're at all able, I highly recommend moving to one of the actually maintained image-based PDF renderers. I'm stuck with this one because I require clickable links in the PDF, and require embedding within Composables (e.g. not a standalone fragment).

Will these offices that I have put solve the 16kb problem to be accepted on google play?

**Comment by Maromax-4002** [comment]
> [@marain87](https://github.com/marain87) Yes I am using correct implementation('com.github.marain87:AndroidPdfViewer:3.2.7') dependency with maven { url 'https://jitpack.io' }
> <img alt="Image" width="2000" height="1214" src="https://private-user-images.githubusercontent.com/220543064/465853523-6f652285-bba0-4e20-b6e0-27df5ef669d1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTc1MTAxMjgsIm5iZiI6MTc1NzUwOTgyOCwicGF0aCI6Ii8yMjA1NDMwNjQvNDY1ODUzNTIzLTZmNjUyMjg1LWJiYTAtNGUyMC1iNmUwLTI3ZGY1ZWY2NjlkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkxMFQxMzEwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjdhZTUzMDgxYjE5Y2Y5OGI0YmNiODdjZTJmOTE5MmEyNGQyYzY2YWVhOTI1MDc0YzZlZjI1YjE2MmQxZWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PeqetxJH-G0g_HcRPbGAUXNYLyPNeN5exAXtRK7Dnjs">

Can you send me the so files for pdfium that I use search and I did not find the size 16kb only 4kb

**Comment by slyvelikov** [comment]
Hi guys ! Can someone please give me a more deep of explanation on how to replace this 'com.github.mhiew:android-pdf-viewer:3.2.0-beta.3' with a working one which is compatible with the google 16KB policy. Cheers!

**Comment by anishsonismtlabs-max** [comment]
Hi everyone! @slyvelikov  You just need to remove the existing dependency com.github.mhiew:android-pdf-viewer:3.2.0-beta.3 and replace it with com.github.marain87:AndroidPdfViewer:3.2.7.

**Comment by achatina** [comment]
@marain87 Thanks! You are a saver!

**Comment by marain87** [comment]
Hi @imilakovic  Based on your other post, it seems your project has other .so files. It's possible that one of these files doesn't support a 16KB page size.
You can try using the command-line script from the Android documentation to check the .so files in your project.

Ref: [https://developer.android.com/guide/practices/page-sizes?hl=en#elf-alignment](https://developer.android.com/guide/practices/page-sizes?hl=en#elf-alignment)

**Comment by Sadheer** [comment]
so what is the solution of this issue     implementation("com.github.mhiew:android-pdf-viewer:3.2.0-beta.3")
i am  using this lib and they not wokr in andorid 15 + and show the same issue that is above

**Comment by Sadheer** [comment]
whne i used marain lib then they show me thsi issue in build


Failed to resolve: com.github.marain87:AndroidPdfViewer:3.2.7
Show in Project Structure dialog
Show Details
Affected Modules: app
>> Ask Gemini

**Comment by marain87** [comment]
> whne i used marain lib then they show me thsi issue in build
> 
> Failed to resolve: com.github.marain87:AndroidPdfViewer:3.2.7 Show in Project Structure dialog Show Details Affected Modules: app
> 
> > > Ask Gemini

Have you add maven { url 'https://jitpack.io' } and tried implementation 'com.github.marain87:AndroidPdfViewer:3.2.8' ?
