### ISSUE TITLE
com.github.barteksc:android-pdf-viewer:2.8.2 Not found in mavenCentral

### ISSUE THREAD

**Issue by SESA676144** [DImuthuUpe/AndroidPdfViewer#1201]
com.github.barteksc:android-pdf-viewer:2.8.2 Not found in maven or mavenCentral But its present in jcenter.
Can you let me know what is happening. Till 7th Aug 2024, without maven(url = "https://jcenter.bintray.com"), pdf library was working but not now. It gives not found error

**Comment by provadriennabonne** [comment]
Same here. It's especially problematic as jcenter is sunsetting August 15th: see here https://jfrog.com/blog/jcenter-sunset/

Could you bring back the 2.8.2 artifact to a maven repo / mavenCentral?

**Comment by George1297** [comment]
Same here. It was working last month

**Comment by bkeresztes** [comment]
Same here, I cannot use the latest version, have to use the 2.8.2, but now I cannot build the project that worked a few weeks ago.
Has anyone found a solution for this?

**Comment by abir-cse** [comment]
Same here :(

**Comment by George1297** [comment]
There is no scope for this library now as its not part of maven.
So i suggest migration to this library

io.github.afreakyelf:Pdf-Viewer:2.1.1

It is also simple and straight forward

**Comment by iip-ritase** [comment]
is this paid repo now?
i cant run this repo anymore

**Comment by George1297** [comment]
Its not paid, its not available now, gone!!

**Comment by praveenraikar** [comment]
Facing same issue, when can this be in maven central @DImuthuUpe ?

**Comment by sarathZam** [comment]
com.github.DImuthuUpe:AndroidPdfViewer:$VERSION

this worked for me

**Comment by import-tushar** [comment]
same issue

**Comment by ari-github** [comment]
> `com.github.DImuthuUpe:AndroidPdfViewer:$VERSION`
> 
> this worked for me

Worked for me with version `2.8.1`
```
com.github.DImuthuUpe:AndroidPdfViewer:2.8.1
```

**Comment by RahamathFern** [comment]
Hi.,

We have encountered the same issue in our project with these libraries.

```
Could not find com.siimkinks.sqlitemagic:sqlitemagic-plugin:0.23.1.
Could not find com.williamww:silky-signature:0.1.0. 
Could not find com.kingfisherphuoc:easy-file-folder-picker-dialog:1.4.
Could not find com.romandanylyk:pageindicatorview:1.0.1.
```
Alternatively, we have to using this way.!

siimkinks.sqlitemagic -> https://jitpack.io/#SiimKinks/sqlitemagic/0.23.0
williamww:silky-signature -> downgrade the version (0.0.6)
kingfisherphuoc:easy-file-folder-picker-dialog -> locally adding the .**aar** files
romandanylyk:pageindicatorview -> locally adding the **.aar** files

**Note:** After integrating the SQLite Magic library from jitpack, I encountered a database initialization error in the SqliteMagic class files.

Error: 
```
E: FATAL EXCEPTION: main
    Process: co.nexlabs.fern.dev, PID: 3369
    java.lang.RuntimeException: Unable to create application co.nexlabs.fern.app.App: java.lang.IllegalStateException: Error initializing database. Make sure there is at least one model annotated with @Table
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5463)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6176)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.IllegalStateException: Error initializing database. Make sure there is at least one model annotated with @Table
        at com.siimkinks.sqlitemagic.SqliteMagic.openConnection(SqliteMagic.java:104)
        at com.siimkinks.sqlitemagic.SqliteMagic$DatabaseSetupBuilder.openDefaultConnection(SqliteMagic.java:215)
        at co.nexlabs.fern.app.App.onCreate(App.java:43)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5460)
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6176) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 
     Caused by: java.lang.RuntimeException: Looks like SqliteMagic gradle plugin processor did not run. Please make sure that project is configured correctly
        at com.siimkinks.sqlitemagic.SqlUtil.getDbVersion(SqlUtil.java:68)
        at com.siimkinks.sqlitemagic.SqliteMagic.openConnection(SqliteMagic.java:92)
        at com.siimkinks.sqlitemagic.SqliteMagic$DatabaseSetupBuilder.openDefaultConnection(SqliteMagic.java:215) 
        at co.nexlabs.fern.app.App.onCreate(App.java:43) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5460) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6176) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 
```

**Comment by Liam6666** [comment]
I was facing same issue in my project, just put jcenter() into repositories of both buildscript allprojects that will be working.

![image](https://github.com/user-attachments/assets/4d89e698-9c69-4daf-9d34-51208bdc3f47)

**Comment by applefanbois** [comment]
So this thing is forever gone?

**Comment by Zhuinden** [comment]
There is a fairly up to date fork in https://github.com/marain87/AndroidPdfViewer although I am going to have to clone it and fix it locally myself, so that's great.
