### ISSUE TITLE
Android  compatibility

### ISSUE THREAD

**Issue by akramraza2** [DImuthuUpe/AndroidPdfViewer#1216]
While loading a pdf file in android  device, getting following error and the pdf doesn' load.

 No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
alamaan.ois                         load pdf error (Ask Gemini)
                                    java.lang.UnsatisfiedLinkError: No implementation found for long com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(int, java.lang.String) (tried Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument and Java_com_shockwave_pdfium_PdfiumCore_nativeOpenDocument__ILjava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
                                    	at com.shockwave.pdfium.PdfiumCore.nativeOpenDocument(Native Method)
                                    	at com.shockwave.pdfium.PdfiumCore.newDocument(PdfiumCore.java:135)
                                    	at com.github.barteksc.pdfviewer.source.FileSource.createDocument(FileSource.java:38)
                                    	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:53)
                                    	at com.github.barteksc.pdfviewer.DecodingAsyncTask.doInBackground(DecodingAsyncTask.java:27)
                                    	at android.os.AsyncTask$3.call(AsyncTask.java:394)
                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by akramraza2** [comment]
Here's an important update. The issue happens with android 15 devices which have 16KB kernel pages. Here's the behavior change for it. [https://developer.android.com/about/versions/15/behavior-changes-all#16-kb](url)

**Comment by marain87** [comment]
ref to #1191
