### ISSUE TITLE
[Crash] PDFView.java line 859

### ISSUE THREAD

**Issue by ldimitroff** [DImuthuUpe/AndroidPdfViewer#927]
I'm having reports of this issue. Haven't found a way to reproduce it but it's really affecting the metrics. Any thoughts on how to capture this issue?

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'float com.github.barteksc.pdfviewer.PdfFile.getMaxPageHeight()' on a null object reference
       at com.github.barteksc.pdfviewer.PDFView.moveTo(PDFView.java:859)
       at com.github.barteksc.pdfviewer.PDFView.moveTo(PDFView.java:813)
       at com.github.barteksc.pdfviewer.AnimationManager$XAnimation.onAnimationUpdate(AnimationManager.java:133)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1374)
       at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1298)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1339)
       at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:715)
       at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:738)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:781)
       at android.view.Choreographer.doCallbacks(Choreographer.java:592)
       at android.view.Choreographer.doFrame(Choreographer.java:559)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:767)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5597)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by ldimitroff** [comment]
Seems that for some reason the PDF View get's recycled and then PdfFile is null at the moment of trying to move to... Crashlytics logs throws that several devices are in background. 

Any help?

**Comment by 1stmetro** [comment]
If you load your pdf and rotate does it retain the pdf ?

**Comment by ldimitroff** [comment]
Yes, it's going trough the recreation path. 

Here's some snippet of what I have: 


```
override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(layoutId)

        pdfUri = intent.getParcelableExtra(EXTRA_URI)

        pdfView.fromUri(pdfUri)
                .pageSnap(true)
                .autoSpacing(true)
                .enableSwipe(true)
                .pageFitPolicy(resources.configuration.orientation.run {
                    if (this == Configuration.ORIENTATION_LANDSCAPE) {
                        FitPolicy.WIDTH
                    } else {
                        FitPolicy.BOTH
                    }
                })
                .swipeHorizontal(true)
                .defaultPage(savedInstanceState?.getInt(CURRENT_PDF_PAGE) ?: 0)
                .onPageChange(pdfViewPageChangeListener)
                .load()
    }

    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)

        outState.putInt(CURRENT_PDF_PAGE, pdfView.currentPage)
    }

```

**Comment by ldimitroff** [comment]
So seems like the Animator keeps working even in the background and when cancelled. 

 ```
class XAnimation extends AnimatorListenerAdapter implements AnimatorUpdateListener {

        @Override
        public void onAnimationUpdate(ValueAnimator animation) {
            float offset = (Float) animation.getAnimatedValue();
            pdfView.moveTo(offset, pdfView.getCurrentYOffset());
            pdfView.loadPageByOffset();
        }
```

**Comment by ImportEffort** [comment]
> So seems like the Animator keeps working even in the background and when cancelled.
> 
> ```
> class XAnimation extends AnimatorListenerAdapter implements AnimatorUpdateListener {
> 
>        @Override
>        public void onAnimationUpdate(ValueAnimator animation) {
>            float offset = (Float) animation.getAnimatedValue();
>            pdfView.moveTo(offset, pdfView.getCurrentYOffset());
>            pdfView.loadPageByOffset();
>        }
> ```

I have the same problem

**Comment by AndrLin** [comment]
I had the same problem, but I couldn't reproduce it. I can only try the following modifications.
```
public void moveTo(float offsetX, float offsetY, boolean moveHandle) {
    if (pdfFile == null || recycled) return;
    ....
}
```

**Comment by ldimitroff** [comment]
> I had the same problem, but I couldn't reproduce it. I can only try the following modifications.
> 
> ```
> public void moveTo(float offsetX, float offsetY, boolean moveHandle) {
>     if (pdfFile == null || recycled) return;
>     ....
> }
> ```

Correct, I had to do the same, I had to modify the visibility of some methods in order to do my own customization on my side: 

```
class CustomPDFView(context: Context, set: AttributeSet) : PDFView(context, set) {

    var onErrorCaptured: (() -> Unit)? = null

    override fun fromUri(uri: Uri?): Configurator =
            runCatching {
                uri?.let {
                    super.fromUri(it)
                } ?: throw IllegalArgumentException()
            }.onFailure {
                onErrorCaptured?.invoke()
            }.getOrElse {
                super.fromUri(Uri.EMPTY)
            }

    override fun moveTo(offsetX: Float, offsetY: Float, moveHandle: Boolean) {
        runCatching {
            super.moveTo(offsetX, offsetY, moveHandle)
        }.onFailure {
            Timber.e(it, "moveTo crash captured.")
            onErrorCaptured?.invoke()
        }
    }

    override fun loadPageByOffset() {
        runCatching {
            super.loadPageByOffset()
        }.onFailure {
            Timber.e(it, "loadPageByOffset crash captured.")
            onErrorCaptured?.invoke()
        }
    }
}
```
